name: MultiTeleport
version: 1.15.2
main: io.github.dice10.multiteleport.MultiTeleport
api-version: 1.13
authors: [DICE10]

commands:
  ntp:
    usage: /<Command> <x> <y> <z>
    description:  "通常テレポート"

  mtp:
    usage: /<Command> [nether/the-end/world]
    description: "ディメンション間のテレポート"

  test:

  anvil:
